apiVersion: v1
kind: Service
metadata:
  name: {{ include "llmtrans.fullname" . }}-api
  labels: {{- include "llmtrans.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "llmtrans.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.service.apiPort }}
      targetPort: http
---
{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "llmtrans.fullname" . }}-ui
  labels: {{- include "llmtrans.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "llmtrans.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
  ports:
    - name: http
      port: {{ .Values.service.uiPort }}
      targetPort: http
{{- end }}
